version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: drkatyayini
      PGDATA: /data/postgres
    volumes:
       - postgresdrk:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres

  django:
    image: apoorvabhishek/dr-katyayini:2.0
    environment:
      USER_NAME: admin
      USER_PWD: admin
      HOST: postgres
      PORT: 5432
    ports:
      - "8000:8000"
    depends_on: 
      postgres:
        condition: service_healthy
    restart: unless-stopped
  
  nginx:
    image: apoorvabhishek/drk-nginx:1.0
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
    - django

volumes:
    postgresdrk:
    static_volume:
    media_volume: