# Generated by Django 4.1.2 on 2022-10-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='submission_date',
            new_name='date_of_examination',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='description',
            new_name='drug_history',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='medicines',
            new_name='prescribed_medicines',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Murliachak', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='bp',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='clubbing',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='cyanosio',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='edenro',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='history_of_presenting_complaint',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='lcterus',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='lumph_adenopathy',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pallor',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='past_medical_history',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='presenting_complaint',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='pulse_rate',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='personal_history',
            field=models.ManyToManyField(blank=True, to='clinic.personalhistory'),
        ),
    ]
